name: Keep Supabase Alive

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 */3 * *'  # Every 3 days at 00:00 UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call keepalive endpoint
        run: |
          curl -X GET https://the-wild-oasis-website-next-js-application.vercel.app/api/keepalive
