name: Keep Supabase Alive

on:
  workflow_dispatch:  # 👈 allows manual triggering
  schedule:
    - cron: '0 12 * * 0'  # every Sunday at noon UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call keepalive endpoint
        run: |
          curl -X GET https://your-project.vercel.app/api/keepalive
